### PR TITLE
Cleaned up code

### PR DESCRIPTION
**Pull request by RexAttaque**
Thank you for your contribution, it's a pretty nice idea. Now this is to help you out as the code was not really standard for lua.

-Variables are now local or part of the ctld table. This is important to not step on other scripts which might make use of global variables as was the case previously in your code (match, _match, _bluePlayers, _redPlayers and AddPlayerAircraftByType()). 
For example someone might name his script "match" just like "ctld" uses the ctld global variable. So if that was the case you'd have a lot of weird behaviors and a lot of errors. Avoid using global variables at all costs.

-Refactored the code to make use of key value pairs in the for loops. A tables contains values which are stored under a certain key. The key is sometimes numeric as is the case for ctld.transportPilotNames but not always. 
It is safer, cleaner (in writing) and more compact to use the "for _key,_value in pairs(table) do" formulation. As you can see this way I can also run through all the players of red and blue with a single for loop and not two separate ones, there is less redundant code.

-Optimized the code (this is minor) by first checking if the player unit name needs to be added at all in the first place, before going through each aircraft type.

-Added logging code, this is of capital importance when debugging. For ctld this is made pretty easy, ctld.logDebug() and ctld.logTrace() allow to push text lines in your dcs.log (I recommend using logExpert to monitor it while you're testing code). The debug and trace toggles at the beginning of ctld.lua control if logTrace and or logDebug calls will work. 
You then have ctld.p() which transforms tables into strings, in practice you should make everything go through ctld.p() before sending it to ctld.logTrace() or logDebug(). This is because you might not know when something is a table or just a value that can be converted to a string.

Now I tested this in singleplayer, with a huey only. Please run tests in multiplayer if able and with the mods that you intend this to work with.

### CODE REVIEW

**Comment by Queton1-1** [comment]
> Thank you for your contribution, it's a pretty nice idea. Now this is to help you out as the code was not really standard for lua.
> 
> -Variables are now local or part of the ctld table. This is important to not step on other scripts which might make use of global variables as was the case previously in your code (match, _match, _bluePlayers, _redPlayers and AddPlayerAircraftByType()). For example someone might name his script "match" just like "ctld" uses the ctld global variable. So if that was the case you'd have a lot of weird behaviors and a lot of errors. Avoid using global variables at all costs.
> 
> -Refactored the code to make use of key value pairs in the for loops. A tables contains values which are stored under a certain key. The key is sometimes numeric as is the case for ctld.transportPilotNames but not always. It is safer, cleaner (in writing) and more compact to use the "for _key,_value in pairs(table) do" formulation. As you can see this way I can also run through all the players of red and blue with a single for loop and not two separate ones, there is less redundant code.
> 
> -Optimized the code (this is minor) by first checking if the player unit name needs to be added at all in the first place, before going through each aircraft type.
> 
> -Added logging code, this is of capital importance when debugging. For ctld this is made pretty easy, ctld.logDebug() and ctld.logTrace() allow to push text lines in your dcs.log (I recommend using logExpert to monitor it while you're testing code). The debug and trace toggles at the beginning of ctld.lua control if logTrace and or logDebug calls will work. You then have ctld.p() which transforms tables into strings, in practice you should make everything go through ctld.p() before sending it to ctld.logTrace() or logDebug(). This is because you might not know when something is a table or just a value that can be converted to a string.
> 
> Now I tested this in singleplayer, with a huey only. Please run tests in multiplayer if able and with the mods that you intend this to work with.

Thanks a lot for your feedback and advices.
I will test and check when i can get the time.

**Comment by RexAttaque** [comment]
There we go, now it's done at the CTLD init instead of every 10s.

**Comment by Queton1-1** [comment]
> There we go, now it's done at the CTLD init instead of every 10s.

Very Nice, thanks
I didn't know Mist could pass through, excellent.

As you're seems to be familiar with Mist and lua tricks, 
CTLD as a limitation for a long time,
(and i don't see anything related to in CTLD Changelogs)
It's mandatory to keep one unit per group (or one human player per group) as the added weight by crates or soldiers apply to each member of the group.
Do you know if it's possible to go over this limitation?

**Comment by RexAttaque** [comment]
> > There we go, now it's done at the CTLD init instead of every 10s.
> 
> Very Nice, thanks I didn't know Mist could pass through, excellent.
> 
> As you're seems to be familiar with Mist and lua tricks, CTLD as a limitation for a long time, (and i don't see anything related to in CTLD Changelogs) It's mandatory to keep one unit per group (or one human player per group) as the added weight by crates or soldiers apply to each member of the group. Do you know if it's possible to go over this limitation?

It is not possible to go over this limitation no, not practicaly, you can not add radio menus to units individually so you will not be able to know which group member triggers a command and so can not know who to give the crate to, who to use as a reference for distances etc.

The only way around this that I know of (which is awful for the users), is to ask the user to give his unit number every time he calls a command. Basically, you click on unpack crate say, then there is another radio menu layer that asks you if you are unit # 1 or # 2 etc.

**Comment by Queton1-1** [comment]
> > > There we go, now it's done at the CTLD init instead of every 10s.
> > 
> > Very Nice, thanks I didn't know Mist could pass through, excellent.
> > 
> > As you're seems to be familiar with Mist and lua tricks, CTLD as a limitation for a long time, (and i don't see anything related to in CTLD Changelogs) It's mandatory to keep one unit per group (or one human player per group) as the added weight by crates or soldiers apply to each member of the group. Do you know if it's possible to go over this limitation?
> 
> It is not possible to go over this limitation no, not practicaly, you can not add radio menus to units individually so you will not be able to know which group member triggers a command and so can not know who to give the crate to, who to use as a reference for distances etc.
> 
> The only way around this that I know of (which is awful for the users), is to ask the user to give his unit number every time he calls a command. Basically, you click on unpack crate say, then there is another radio menu layer that asks you if you are unit # 1 or # 2 etc.

You're right, this way is awful and complex.

I made this conclusion too (i wanted to make menu for unit in group in a mission and it was not possible.)
but i hoped for an other solution.

Thank you very much for your tricks and answers 😉

**Pull request merged**
